[package]
name = "axtop"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = { version = "0.6.12", features = ["macros", "ws"]}
serde_json = "1.0.95"
sysinfo = "0.28.4"
tokio = { version = "1.27.0", features = ["full"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
